name: Avvio Estrazione Notizie - GIORNALI

on:
  workflow_dispatch: # Solo attivazione manuale con bottone

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: |
          pip install -r requirements.txt

      - name: Esegui il Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        run: python -u bot_giornali.py
